version: "3.8"
services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      # マウントと同時にDB作成
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my.cnf:/etc/mysql/my.cnf
    restart: always
    platform: linux/arm64/v8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - 3306:3306

  api:
    build:
      context: .
      dockerfile: api/docker/Dockerfile
    volumes:
      - ./api/src/:/api/src
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db_data:
