FROM golang:1.20-alpine as build
WORKDIR /api

ENV GOPATH $HOME/api
ENV PATH $PATH:$GOPATH/bin

RUN apk add --no-cache git

COPY ./api/src /api/src

RUN go install github.com/cosmtrek/air@latest
RUN go install github.com/google/wire/cmd/wire@latest
RUN go install github.com/99designs/gqlgen@latest
WORKDIR /api/src

RUN go mod tidy
RUN go build -o main main.go

# マルチステージビルド
FROM golang:1.20-alpine
RUN apk upgrade --update && \
    apk add --no-cache tzdata

COPY --from=build /api/src/main /api/src/main
COPY --from=build /api/bin/air /usr/local/bin/
COPY --from=build /api/bin/wire /usr/local/bin/
COPY --from=build /api/bin/gqlgen /usr/local/bin/

WORKDIR /api/src

# airを実行
CMD ["air"]

# Go run main.goを実行
# CMD ["go", "run", "main.go"]
